### ISSUE TITLE
您好！请问运行run.py后抓取到的有效数据项很少的可能原因是什么啊？

### ISSUE THREAD

**Issue by hardworkRachel** [yeeeqichen/MedicalKG#2]
![image](https://github.com/yeeeqichen/MedicalKG/assets/90208180/9b7b7fcf-d160-4ad0-bcfe-ef918383bff7)
返回信息：downloader/request_bytes': 385560,
 'downloader/request_count': 696,
 'downloader/request_method_count/POST': 696,
 'downloader/response_bytes': 26526152,
 'downloader/response_count': 696,
 'downloader/response_status_count/200': 676,
 'downloader/response_status_count/502': 11,
 'downloader/response_status_count/504': 9,
 'elapsed_time_seconds': 155.721246,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 10, 27, 8, 40, 40, 834034, tzinfo=datetime.timezone.utc),
 'item_scraped_count': 173,
 'log_count/DEBUG': 870,
 'log_count/INFO': 12,
 'log_count/WARNING': 2,
 'request_depth_max': 1,
 'response_received_count': 676,
 'retry/count': 20,
 'retry/reason_count/502 Bad Gateway': 11,
 'retry/reason_count/504 Gateway Time-out': 9,
 'scheduler/dequeued': 1372,
 'scheduler/dequeued/memory': 1372,
 'scheduler/enqueued': 1372,
 'scheduler/enqueued/memory': 1372,
 'splash/execute/request_count': 4,
 'splash/execute/response_count/200': 4,
 'splash/render.html/request_count': 672,
 'splash/render.html/response_count/200': 672,
 'splash/render.html/response_count/502': 11,
 'splash/render.html/response_count/504': 9,
 'start_time': datetime.datetime(2023, 10, 27, 8, 38, 5, 112788, tzinfo=datetime.timezone.utc)}
2023-10-27 16:40:40 [scrapy.core.engine] INFO: Spider closed (finished)
其中运行几次的结果'item_scraped_count'最多时项数为507，求大佬答疑

**Comment by yeeeqichen** [comment]
经检查，原因为 https://baike.baidu.com/wikitag/taglist?tagId=75953 这类网页返回的数据发生了变化（比两年前大大减少，你可以打开不断下拉并检查数量）。

**Comment by hardworkRachel** [comment]
大量返回信息：DEBUG: Crawled (200) <GET http://baike.baidu.com/item/%E6%9C%A8%E9%80%9A/936152 via http://localhost:8050/render.html> (referer: None)是因为百度的反爬机制吗，是否需要搭建代理池呢

**Comment by yeeeqichen** [comment]
原因应该是百度限制了百科页面列表的返回数量，暂时没有很好的办法解决

**Comment by hardworkRachel** [comment]
好的，感谢答疑！

**Comment by hardworkRachel** [comment]
您好！非常抱歉再次叨扰您，冒昧询问一下这个项目mongodb中的44k条三元组数据方便导出分享一下吗，非常感谢！
